apiVersion: v1
kind: Pod
metadata:
  name: pytest-playwright
  labels:
    app: pytest-playwright
spec:
  containers:
  - name: pytest-playwright
    image: 326226782879.dkr.ecr.us-east-1.amazonaws.com/pytest-playwright-test:latest
    imagePullPolicy: Always
    command: ["pytest", "-n", "3", "--browser", “firefox”, "--html=/app/reports/report.html"]
    volumeMounts:
    - name: reports
      mountPath: /app/reports
  restartPolicy: Never
  volumes:
  - name: reports
    emptyDir: {}
