name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Install Allure Commandline
      run: |
        sudo apt update
        sudo apt install openjdk-11-jdk
        cd /tmp
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.tgz
        tar -zxvf allure-2.21.0.tgz
        sudo mv allure-2.21.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        allure --version
    - name: Run your tests
      run: pytest --alluredir reports/allure-results
    - name: Generate Allure Report
      run: allure serve reports/allure-results
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-results/
      #run: pytest --tracing=retain-on-failure
      #run: pytest -s -v --html=reports/report.html --video=on --capture=tee-sys
   # - uses: actions/upload-artifact@v4
   #   if: ${{ !cancelled() }}
   #   with:
   #     name: playwright-report
   #     path: reports/
