name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      #run: pytest --tracing=retain-on-failure
      run: pytest -s -v --html=reports/report.html --video=on --capture=tee-sys
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: reports/
    - uses: actions/upload-artifact@master
      with:
          name: allure-results
          path: allure-results
    - name: Load Test Report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages
    - name: Build Test Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      id: allure-report
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 1
    - name: Publish report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history