name: Run Pytest Playwright on Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

#    env:
#      KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Store the Kubernetes config as a secret in GitHub

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your AWS region

    - name: Update Kubeconfig
      run: |
          aws eks --region us-east-1 update-kubeconfig --name pytest-playwright-cluster


    # Step 1: Build Docker Image for Pytest Playwright Tests
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/pytest-playwright:latest .
        docker push ghcr.io/${{ github.repository }}/pytest-playwright:latest

    # Step 1: Install Kubectl and set up
    - name: Install kubectl
      run: | 
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

#    # Set up KUBECONFIG
#    - name: Set up KUBECONFIG
#      run: |
#        mkdir -p ~/.kube
#        echo "${{ secrets.KUBECONFIG}}" > ~/.kube/config
#        chmod 600 ~/.kube/config
#
#    # Verify kubectl configuration
#    - name: Verify Kubernetes cluster access
#      run:
#        kubectl config view
#    - name: Verify Get nodes
#      run: |
#        kubectl cluster-info
#        kubectl config use-context docker-desktop
#       kubectl get nodes
#    - name: Use current context
#      run:
#        kubectl config use-context docker-desktop

#    - name: Set up kubectl
#      uses: azure/setup-kubectl@v3
#      with:
#        version: 'v1.22.0'
    - name: Deploy Pod to Kubernetes
      run: |
        kubectl apply -f k8s/pytest-playwright-pod.yaml --validate=false

    - name: Wait for Pod to be Running
      run: |
        kubectl wait --for=condition=Ready pod/pytest-playwright --timeout=60s

    # Step 3: Run Pytest Playwright Tests in Kubernetes Pod
    - name: Run Playwright Tests
      run: |
        kubectl exec pytest-playwright -- pytest -n 3 --browser chromium --html=reports/report.html

    # Step 4: Fetch Test Results (HTML Report)
    - name: Copy Test Report to Local
      run: |
        kubectl cp pytest-playwright:/app/reports/report.html ./reports/report.html

    # Step 5: Upload Test Results to GitHub
    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: ./reports/report.html
